import React, { useState } from 'react';
import { 
  GitCompare, 
  Sparkles, 
  ShieldCheck, 
  Check, 
  X, 
  Search, 
  TrendingUp, 
  Zap, 
  Lock,
  ArrowRight
} from 'lucide-react';
import { CompetitorData } from '../types';

interface CompetitorMatrixProps {
  competitors: CompetitorData[];
  onAnalyzeNewCompetitor: (competitorName: string) => void;
}

export const CompetitorMatrix: React.FC<CompetitorMatrixProps> = ({
  competitors,
  onAnalyzeNewCompetitor,
}) => {
  const [customCompetitor, setCustomCompetitor] = useState('');

  const handleCustomSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!customCompetitor.trim()) return;
    onAnalyzeNewCompetitor(customCompetitor.trim());
    setCustomCompetitor('');
  };

  return (
    <div id="competitor-intelligence-module" className="space-y-4">
      {/* Header Banner */}
      <div className="p-4 rounded-xl bg-slate-900/80 border border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div>
          <div className="flex items-center space-x-2">
            <GitCompare className="w-5 h-5 text-cyan-400" />
            <h3 className="text-base font-semibold text-slate-100">
              Competitor Analysis & Market Intelligence ("Companiring")
            </h3>
          </div>
          <p className="text-xs text-slate-400 mt-1">
            Real-time market positioning, pricing tiers, feature disparity, and automated sales battlecards generated by Jack.
          </p>
        </div>

        {/* Custom Competitor Analysis Input */}
        <form onSubmit={handleCustomSubmit} className="flex items-center space-x-2">
          <input
            type="text"
            placeholder="Compare another platform (e.g. Jasper, Salesforce Agentforce)..."
            value={customCompetitor}
            onChange={(e) => setCustomCompetitor(e.target.value)}
            className="w-full sm:w-64 px-3 py-1.5 rounded-lg bg-slate-950 border border-slate-800 text-xs text-slate-200 placeholder-slate-500 focus:outline-none focus:border-cyan-500"
          />
          <button
            type="submit"
            disabled={!customCompetitor.trim()}
            className="px-3 py-1.5 rounded-lg bg-cyan-600 hover:bg-cyan-500 disabled:opacity-50 text-white text-xs font-semibold flex items-center space-x-1 transition-colors whitespace-nowrap"
          >
            <Sparkles className="w-3.5 h-3.5" />
            <span>Analyze</span>
          </button>
        </form>
      </div>

      {/* Feature & Security Comparison Matrix */}
      <div className="rounded-xl bg-slate-900/80 border border-slate-800 overflow-hidden">
        <div className="p-4 border-b border-slate-800 flex items-center justify-between">
          <h4 className="text-sm font-semibold text-slate-100">Enterprise AI Assistant Competitive Landscape</h4>
          <span className="text-xs text-cyan-400 font-mono">Updated Today</span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs border-collapse">
            <thead>
              <tr className="bg-slate-950/70 border-b border-slate-800 text-slate-400 font-medium">
                <th className="p-3.5 pl-4">Platform Capability</th>
                <th className="p-3.5 text-cyan-300 font-semibold bg-cyan-950/20 border-x border-cyan-500/20">
                  ★ Jack Executive AI Stack
                </th>
                <th className="p-3.5 text-slate-300">OmniFlow Cloud</th>
                <th className="p-3.5 text-slate-300">SiriBiz Suite</th>
                <th className="p-3.5 text-slate-300">MarketNexus</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60 text-slate-300">
              <tr>
                <td className="p-3.5 pl-4 font-medium text-slate-200">
                  Safeguard Staged Actions (Draft, Don't Blindly Send)
                </td>
                <td className="p-3.5 bg-cyan-950/20 border-x border-cyan-500/20 font-semibold text-emerald-400 flex items-center gap-1.5">
                  <Check className="w-4 h-4 text-emerald-400" /> Full Human-in-Loop Queue
                </td>
                <td className="p-3.5 text-slate-400">Manual templates only</td>
                <td className="p-3.5 text-rose-400 flex items-center gap-1">
                  <X className="w-4 h-4 text-rose-400" /> Auto-sends (High risk)
                </td>
                <td className="p-3.5 text-slate-400">Complex rules engine</td>
              </tr>

              <tr>
                <td className="p-3.5 pl-4 font-medium text-slate-200">
                  Voice-Reactive Siri-Style Interface
                </td>
                <td className="p-3.5 bg-cyan-950/20 border-x border-cyan-500/20 font-semibold text-emerald-400 flex items-center gap-1.5">
                  <Check className="w-4 h-4 text-emerald-400" /> Real-time Speech + Waveform
                </td>
                <td className="p-3.5 text-rose-400 flex items-center gap-1">
                  <X className="w-4 h-4 text-rose-400" /> No Voice (Text-only)
                </td>
                <td className="p-3.5 text-slate-300 flex items-center gap-1">
                  <Check className="w-4 h-4 text-emerald-400" /> Basic Consumer Voice
                </td>
                <td className="p-3.5 text-rose-400 flex items-center gap-1">
                  <X className="w-4 h-4 text-rose-400" /> No Voice
                </td>
              </tr>

              <tr>
                <td className="p-3.5 pl-4 font-medium text-slate-200">
                  Data Privacy & Encryption Standard
                </td>
                <td className="p-3.5 bg-cyan-950/20 border-x border-cyan-500/20 font-semibold text-emerald-400 flex items-center gap-1.5">
                  <ShieldCheck className="w-4 h-4 text-emerald-400" /> AES-256 Client-Side Enclave
                </td>
                <td className="p-3.5 text-slate-400">Standard TLS at rest</td>
                <td className="p-3.5 text-slate-400">Cloud stored (Unencrypted vault)</td>
                <td className="p-3.5 text-slate-300">Enterprise SOC2</td>
              </tr>

              <tr>
                <td className="p-3.5 pl-4 font-medium text-slate-200">
                  Customer Data Model Training Policy
                </td>
                <td className="p-3.5 bg-cyan-950/20 border-x border-cyan-500/20 font-semibold text-emerald-400">
                  Zero Data Training (Strict Privacy)
                </td>
                <td className="p-3.5 text-rose-400">Used for aggregate training</td>
                <td className="p-3.5 text-rose-400">Opt-out required</td>
                <td className="p-3.5 text-slate-300">Isolated VPC</td>
              </tr>

              <tr>
                <td className="p-3.5 pl-4 font-medium text-slate-200">
                  Estimated Monthly Investment
                </td>
                <td className="p-3.5 bg-cyan-950/20 border-x border-cyan-500/20 font-semibold text-cyan-300">
                  $180 / seat (All-Inclusive)
                </td>
                <td className="p-3.5 text-slate-400">$299 - $1,499 / mo</td>
                <td className="p-3.5 text-slate-400">$150 - $800 / mo</td>
                <td className="p-3.5 text-slate-400">$1,200 - $5,000 / mo</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* Competitor Cards & Battlecards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {competitors.map((comp) => (
          <div
            key={comp.id}
            className="p-5 rounded-xl bg-slate-900/80 border border-slate-800 space-y-3 flex flex-col justify-between"
          >
            <div className="space-y-2.5">
              <div className="flex items-start justify-between">
                <div>
                  <h4 className="text-sm font-semibold text-slate-100">{comp.name}</h4>
                  <span className="text-[11px] text-slate-400">Market Share: {comp.marketShare}</span>
                </div>
                <span className="text-xs font-mono font-semibold px-2 py-0.5 rounded bg-slate-800 text-slate-300 border border-slate-700">
                  {comp.pricingTier}
                </span>
              </div>

              <div>
                <span className="text-[11px] text-emerald-400 font-medium">Strengths:</span>
                <ul className="text-xs text-slate-300 list-disc list-inside mt-0.5 space-y-0.5">
                  {comp.primaryStrengths.map((s, idx) => (
                    <li key={idx}>{s}</li>
                  ))}
                </ul>
              </div>

              <div>
                <span className="text-[11px] text-rose-400 font-medium">Vulnerabilities:</span>
                <ul className="text-xs text-slate-400 list-disc list-inside mt-0.5 space-y-0.5">
                  {comp.primaryWeaknesses.map((w, idx) => (
                    <li key={idx}>{w}</li>
                  ))}
                </ul>
              </div>
            </div>

            <div className="pt-3 border-t border-slate-800 text-xs">
              <span className="text-slate-400 font-medium text-[11px]">Our Winning Counter-Angle:</span>
              <p className="text-cyan-300 font-medium mt-1 leading-relaxed bg-cyan-950/20 p-2 rounded border border-cyan-800/30">
                "{comp.ourAdvantage}"
              </p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
